name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: Name of the deployed artifact
                required: true
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifacts@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output Information
              run: echo "Deploying ..."